
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
tasks:
    resource: "@AppBundle/Controller/TaskController.php"
    type:     rest
    prefix:   /api
garden:
    resource: "@GardenBundle/Controller/GardenController.php"
    type:     rest
    prefix:   /api
index:
    pattern:  /index
    defaults: { _controller: AppBundle:Default:index }
fallback:
    pattern:  /app/{url}
    defaults: { _controller: AppBundle:Default:app, url: null }
    requirements:
        url: .*
