<?php

namespace GardenBundle\Repository;

/**
 * GardenItemPercRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenItemPercRepository extends \Doctrine\ORM\EntityRepository
{
}
