<?php

namespace GardenBundle\Repository;

/**
 * GardenDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenDataRepository extends \Doctrine\ORM\EntityRepository
{
}
