<?php

namespace GardenBundle\Repository;

/**
 * GardenTileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenTileRepository extends \Doctrine\ORM\EntityRepository
{
}
