<?php

namespace GardenBundle\Repository;

/**
 * GardenIndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenIndicatorRepository extends \Doctrine\ORM\EntityRepository
{
}
