<?php

namespace GardenBundle\Repository;

/**
 * GardenItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenItemRepository extends \Doctrine\ORM\EntityRepository
{
}
